import { useEffect, useState } from 'react';
import Head from 'next/head';
import {
  UnorderedList, ListItem, Container, Flex, Button, Heading,
} from '@chakra-ui/react';
import { SpotifyData, Track } from './api/spotify';
import { SpotifyLogin } from '../features/spotify-login';
import { useSpotifyContext } from '../features/spotify-context';

const Index = () => {
  const [tracks, setTracks] = useState<Track[] | null>(null);
  const [displayName, setDisplayName] = useState<string>('');
  const { accessToken } = useSpotifyContext();

  useEffect(() => {
    if (!accessToken) {
      return;
    }
    (async () => {
      const res = await fetch(`/api/spotify?token=${accessToken}`);
      const json = await res.json() as SpotifyData;
      setDisplayName(json.user.display_name);
      setTracks(json.tracks);
    })();
  }, [accessToken]);

  const tracksList = tracks?.map((track) => (
    <ListItem key={track.id}>
      {track.song.name}
    </ListItem>
  ));

  let content = null;
  if (accessToken) {
    content = (
      <>
        <Heading as="h1" size="l">
          Logged in as
          {' '}
          {displayName}
        </Heading>
        <UnorderedList>
          {tracksList}
        </UnorderedList>
      </>
    );
  } else {
    content = <SpotifyLogin />;
  }

  return (
    <>
      <Head>
        <title>Spotify Time Warp</title>
        <meta name="description" content="Autogenerated Spotify playlists based on your listening history" />
      </Head>

      <Container maxW="container.xl">
        <Flex direction="column" align="center">
          <Heading as="h1" size="xl" textAlign="center">I make Spotify playlists based on your recent listening history. Spotify Wrapped, but for the past month.</Heading>
          <Flex>
            <Button m="2">Make a playlist of my top songs</Button>
            <Button m="2">Make a playlist of recommendations</Button>
          </Flex>
        </Flex>
        {content}
      </Container>
    </>
  );
};

export default Index;
